name=raw_input("What is Your name?\n")
age=raw_input("How old are You?\n")
place=raw_input("Where are You live?\n")
print("Your name is - "+name+".")
print("Your are "+age+" years old.")
print("Your living place is -  "+place+".")