print("What is your name? ")
name= input("Hello , my name is Rostyk")
print(name)
print("How old are you? ")
age=input("i am 25 years old")
print(age)
print("Where do you live?")
live=input("i live in Lviv")
print(live)